spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/cmms
    #url: jdbc:mariadb://cmms.c9gue80i0enx.us-east-2.rds.amazonaws.com:3306/cmms
    username: root
    #password: root
    password: yuls88!#3
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 10
  
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        'format_sql': true
        dialect: org.hibernate.dialect.MariaDBDialect
        connection.isolation: 2  # READ_COMMITTED

  thymeleaf:
    cache: false
  
  messages:
    basename: messages/messages
    encoding: UTF-8
    fallback-to-system-locale: false
    cache-duration: -1
    use-code-as-default-message: true
    default-locale: ko
  
  web:
    locale: ko
    locale-resolver: fixed

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  file:
    name: logs/application.log
  level:
    org.springframework.security: DEBUG
    com.cmms: DEBUG 
    org.springframework.context.support: TRACE
    org.springframework.context.i18n: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

cmms:
  default-company-id: C0001