# 운영 환경 전용 설정
spring:
  config:
    import:
      - optional:classpath:prod.properties
  
  # 데이터베이스 운영 설정
  datasource:
    url: ${DB_URL:jdbc:mariadb://cmms-prod-db.cluster-xxx.ap-northeast-2.rds.amazonaws.com:3306/cmms?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8}
    username: ${DB_USERNAME:cmms_admin}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.mariadb.jdbc.Driver}
    hikari:
      auto-commit: true
      minimum-idle: 10
      maximum-pool-size: 50
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA 운영 설정
  jpa:
    hibernate:
      ddl-auto: validate  # 운영에서는 validate만 사용
    show-sql: false  # 운영에서는 SQL 로그 비활성화
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  # Thymeleaf 운영 설정
  thymeleaf:
    cache: true  # 운영에서는 캐시 활성화

# 서버 운영 설정
server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# 로깅 운영 설정
logging:
  file:
    name: logs/application.log
    max-size: 100MB
    max-history: 30
  level:
    org.springframework.security: WARN
    com.cmms: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
    root: WARN

# 파일 업로드 운영 설정
file:
  upload:
    root-path: ${FILE_UPLOAD_PATH:/opt/cmms/uploads}
    max-file-size: ${FILE_MAX_SIZE:50MB}
    allowed-file-types: ${FILE_ALLOWED_TYPES:jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx,txt}
    max-file-count: ${FILE_MAX_COUNT:20}
