spring:
  # H2 Database
  datasource:
    url: jdbc:h2:mem:cmmsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA
  jpa:
    hibernate:
      ddl-auto: create-drop # 애플리케이션 실행 시 스키마를 생성하고 종료 시 삭제
    show-sql: true # SQL 쿼리를 로그에 출력
    properties:
      hibernate:
        format_sql: true # SQL을 보기 좋게 포맷팅

logging:
  level:
    org.hibernate.SQL: debug
    com.yulslab: debug
